### ISSUE TITLE
Linking with not all libs

### ISSUE THREAD

**Issue by krojew** [MarcoKoch/conan-libunwind#1]
When using 32bit version (-s arch=x86), the library linked is only libunwind.la, not libunwind-x86.la, which causes many missing symbols. Haven't tested for other architectures, but probably it's the same story.

**Comment by krojew** [comment]
Changing 
`self.cpp_info.libs = ["unwind"]`
to
`self.cpp_info.libs = ["unwind", "unwind-%s" % self.settings.arch]`
fixes the issue

**Comment by MarcoKoch** [comment]
Fixed with 5e186838e6009da6bf58ec9449ec6dd5048838d5.
Thank you!

**Comment by krojew** [comment]
Can you publish your changes to the package repo for 1.2.1?

**Comment by MarcoKoch** [comment]
It should already be in the 'testing' channel.
May I ask you to test whether the testing-package works as expected? I will then also upload to 'stable'.

**Comment by krojew** [comment]
I can confirm the testing chanel works.

**Comment by MarcoKoch** [comment]
Thanks!
I pushed release v1.2.1-1. The package should be available on Bintray as soon as it is through CI.
